---
image: node:14.15.4

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - build

stages:
  - init
  - lint
  - tests
  - build
  - release
  - publish
  - package
  - deploy
  - clean

before_script:
  - make help-frontend

init:
  stage: init
  script:
    - make init-frontend

# lint:
#   stage: lint
#   script:
#     - make lint-frontend

tests:
  stage: tests
  script:
    - make tests-frontend

build:
  stage: build
  script:
    - make build-frontend

publish:
  stage: publish
  script:
    - make publish-frontend

# GitLab Pages requires the job name to be pages.
pages:
  stage: deploy
  script:
      # GitLab pages requires the artifact to be called public.
      - mv build/docs public
  artifacts:
    paths:
      - public
  only:
    - develop