---
image: node:latest

variables:
  ENV: ci
  CI: "true"
  YARN: yarn

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - build

stages:
  - clean
  - lint
  - tests
  - build
  - release
  - package
  - deploy

before_script:
  - make help-frontend
  - echo
  - make init-frontend

# lint:
#   stage: lint
#   script:
#     - make lint-frontend

tests:
  stage: tests
  script:
    - make tests-frontend

build:
  stage: build
  script:
    - make build-frontend
  only:
    - develop

deploy:
  stage: deploy
  script:
      - test -f build/docs/index.html
  artifacts:
    paths:
      - build/docs